apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: html-svc
  labels:
    app: html
    environment: dev
spec:
  type: NodePort
  selector:
    app: html
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
